service: newsletter
variablesResolutionMode: 20210326

frameworkVersion: '2'

plugins:
  - serverless-bundle
  - serverless-cloudformation-sub-variables

custom:
  SubscribedUsersTable:
    name: !Ref UsersSubscriptionTable
    arn: !GetAtt UsersSubscriptionTable.Arn
  bundle:
    linting: false

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  environment:
    STAGE: ${self:provider.stage}
    SUBSCRIBED_USERS_TABLE_NAME: ${self:custom.SubscribedUsersTable.name}
    SEND_GRID_API_KEY: ${env:SEND_GRID_API_KEY}

functions:
  - ${file(resources/lambda/RetrieveSubscribersLambda.yml)}
  - ${file(resources/lambda/NewSubscriberLambda.yml)}
  - ${file(resources/lambda/SendMailLambda.yml)}
  - ${file(resources/lambda/Unsubscribe.yml)}

resources:
  - ${file(resources/dynamo/Tables.yml)}
  - ${file(resources/iam/LambdaPermissions.yml)}
  - ${file(resources/iam/Policies.yml)}
  - ${file(resources/iam/Roles.yml)}
  - ${file(resources/s3/Buckets.yml)}
  - ${file(resources/api_gateway/CORS.yml)}