Resources:
  RetrieveAllSubscribersLambdaPermissionApiGateway:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - ApiGatewayRestApi
    Properties:
      FunctionName: { "Fn::GetAtt": [ SendMailLambdaFunction, Arn ] }
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: arn:aws:lambda:us-west-2:185871847164:function:newsletter-dev-sendMail