name: Deploy Serverless Infrastructure
on:
  push:
    branches:
      - master
jobs:
  deploy-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install Dependencies
        run: >
          npm install -g serverless && \
          node ./node_modules/serverless/bin/serverless plugin install -n serverless-bundle && \
          node ./node_modules/serverless/bin/serverless plugin install -n serverless-cloudformation-sub-variables

      - name: Serverless AWS authentication
        run: node ./node_modules/serverless/bin/serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy
        run: SLS_DEBUG=* node ./node_modules/serverless/bin/serverless deploy -v
