name: Serverless Deployment Prod
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: prod
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: node ./node_modules/serverless/bin/serverless.js plugin install -n serverless-bundle
      - run: node ./node_modules/serverless/bin/serverless.js config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: node ./node_modules/serverless/bin/serverless.js deploy --verbose 
      - run: node ./node_modules/serverless/bin/serverless.js deploy --stage=prod --verbose 
        working-directory: /home/runner/work/ServerlessNewsletter/ServerlessNewsletter/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SEND_GRID_API_KEY: ${{ secrets.SEND_GRID_API_KEY }}
          SLS_DEBUG: 1